version: '3.7'

services:
  php:
     build:
       context: .
       dockerfile: docker/php/Dockerfile
     volumes:
       - ./:/usr/src/app

  nginx:
     image: nginx:1.15.3-alpine
     volumes:
       - ./:/usr/src/app:cached
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
     ports:
       - 80:80
     depends_on:
       - php
